export const kategoriak = [
    {angol: "Echoes of the future", magyar: "A jövő visszhangjai"},
    {angol: "Paths of the unknown", magyar:"Az ismeretlen ösvényei"},
    {angol: "Nomad legacy", magyar:"Nomád örökség"},
    {angol: "Urban chronicles", magyar:"Városi krónikák"},
    {angol: "Post-apocalyptic futurism", magyar:"Poszt-apokaliptikus futurizmus"},
    {angol: "Urban survival", magyar:"Városi túlélés"},
    {angol: "Adaptive fashion", magyar:"Adaptív divat"},
    {angol: "Rebirth and renewal", magyar:"Újjászületés és megújulás"},
    {angol: "Survival through unity", magyar:"Túlélés az egységen keresztül"},
    {angol: "Minimalism and adaptation", magyar:"Minimalizmus és alkalmazkodás"},
    {angol: "Warrior spirit", magyar:"Harcos szellem"},
    {angol: "Celebrating the strength in diversity", magyar:"A sokféleségben rejlő erő ünneplése"},
    {angol: "Cyber survival", magyar:"Kibernetikus túlélés"},
    {angol: "Nomad alchemy", magyar:"Nomád alkímia"},
    {angol: "Uncharted terrain", magyar:"Feltérképezetlen terep"},
    {angol: "Crafting the unknown", magyar:"Az ismeretlen megformálása"},
    {angol: "Survival strategies decoded", magyar:"Túlélési stratégiák dekódolva/megfejtve"},
    {angol: "Beyond tomorrow", magyar:"A holnapon túl"},
    {angol: "Navigating to the unknow", magyar:"Navigálás az ismeretlen felé"},
    {angol: "Escape from dystopia", magyar:"Menekülés a disztópiából"},
    {angol: "Survival strategies: the art of mimicry", magyar:"Túlélési stratégiák: a mimikri művészete"},
]